### ISSUE TITLE
3rd Party Testing on Ubuntu 20.04

### ISSUE THREAD

**Issue by ijonglin** [ijonglin/teclast-f5-ubuntu-finalizer#6]
Need 3rd party to confirm that the modified v5.5 kernel version works on another person's vanilla Ubuntu 20.04 install, and fixes the S3 wake issues with the trackpad

**Comment by ijonglin** [comment]
@Kabbone Can you test the v5.5 kernel?

**Comment by Kabbone** [comment]
sorry, for reaching out so late. I can only test on Archlinux with v5.7.2
