### ISSUE TITLE
Keyboard and touchpad hint

### ISSUE THREAD

**Issue by RussianNeuroMancer** [ijonglin/teclast-f5-ubuntu-finalizer#7]
Hi

I have similar device on hands (Irbis NB111) and I found that keyboard and touchpad is works after wakeup from S3 once I restore vendor's Windows 10 image. After that I can boot back to Linux and keyboard and touchpad now works after wakeup from S3.

However, as soon as device discharge to 0% at least once issue is back and I need to boot Windows 10 again. It's seems like Windows driver HingeAngleDevice could be responsible for restoring keyboard and touchpad function after wakeup from S3. At least this is what other Teclast F5 owners said on 4pda forum

**Comment by RussianNeuroMancer** [comment]
Just in case, here is the factory recovery image: https://1drv.ms/f/s!AtprAlErUyChi19Utgao6PvEpXmY

**Comment by ijonglin** [comment]
Interesting.  I've noted that there are some BIOS settings that need to be disabled to have the mouse work properly, in particular "EC Notification".  So that could also be the issue.

**Comment by RussianNeuroMancer** [comment]
Do you see anything related for enabling disabling here? 
https://github.com/ijonglin/teclast-f5-ubuntu-finalizer/blob/master/dsdt/src/DSDT-FIX-TECLAST-F5-IJL-V8.dsl#L12602
https://github.com/ijonglin/teclast-f5-ubuntu-finalizer/blob/master/dsdt/src/DSDT-FIX-TECLAST-F5-IJL-V8.dsl#L5539

Maybe add line "Name (_S3W, 0x04)" below "Name (_S0W, 0x04)  // _S0W: S0 Device Wake State" in touchpad section? Or maybe there is some GPIO that can be used to wake touchpad after S3 if something (multicontroller?) disable it? HingeAngleDevice has been doing this somehow after all. As for keyboard - I have no idea.

**Comment by RussianNeuroMancer** [comment]
> I've noted that there are some BIOS settings that need to be disabled to have the mouse work properly, in particular "EC Notification"

Oh, I have to add that I don't own Teclast F5 but another similar device - Irbis NB111. It's almost the same, just like JUMPER EZbook X1, but BIOS is different - on Irbis NB111 it's locked down and there is no settings to tinker with, besides basic stuff like boot order, fast boot, etc.

**Comment by ijonglin** [comment]
This DSL file was an merge  of a working Teclast D7 (which didn't have this issue) and the original Teclast-F5 dsdt codebases.   You may want to decompile the https://github.com/ijonglin/teclast-f5-ubuntu-finalizer/blob/master/dsdt/examples/DSDT-F7.dat and see whether the original makes more sense.

**Comment by RussianNeuroMancer** [comment]
> and see whether the unedited original makes more sense

Unfortunately I don't understand DSDT, which is why I asked you here to take a look at [relevant keyboard/touchpad description](https://github.com/ijonglin/teclast-f5-ubuntu-finalizer/issues/7#issuecomment-709735917).

**Comment by jwrdegoede** [comment]
@ijonglin can you perhaps provide a diff (diff -u output) between the original Teclast F5 dsdt.dsl and the fixed F5 dsdt.dsl ?

If you also happen to know which part of the diff helped with the keyboard/touchpad issue then that would be ideal.

**Comment by ijonglin** [comment]
@jwrdegoede Sure, give me a little time -- I'll check in the DSL modifications that I made.  Bump me in a couple of days.

**Comment by ijonglin** [comment]
On a side note, @jwrdegoede, I see that you have also supported AllWinner A10 Fedora Distro -- very cool.   I have one of those running on my local network for giggles.

**Comment by ijonglin** [comment]
Actually, the original DSL file is already checked in.   The diff can be created by running the following command:

`
diff dsdt/examples/DSDT-teclast-f5.dsl dsdt/src/DSDT-FIX-TECLAST-F5-IJL-V8.dsl 
`

The original source of the changes is available from Teclast D7 can be made by running the command from the root of the repo:
`
cd dsdt
make examples/DSDT-F7.dsl
`

But I'll also check that in as well.

**Comment by ijonglin** [comment]
@jwrdegoede  @RussianNeuroMancer  Checked in the originals, so that you can now diff the changes.   I basically did various attempts of merging the code until it finally was stable, based on the relevant trackpad and mouse references that I could see in ACPI.

**Comment by ijonglin** [comment]
@jwrdegoede @RussianNeuroMancer Is there anything else that I can do?   Or can I close this issue out?

**Comment by jwrdegoede** [comment]
@ijonglin thanks for your help. I believe that I have figured out the real problem / cause for the touchpad/kbd not working and I have submitted a patch upstream which should fix this without needing DSDT changes, see:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e5b1032a656e9aa4c7a4df77cb9156a2a651a5f9

So yes I believe that this issue can be closed.

**Comment by ijonglin** [comment]
Oh, excellent.   So what version of the kernel will have this fix incorporated?  That would be super awesome!!!

**Comment by RussianNeuroMancer** [comment]
>  So what version of the kernel will have this fix incorporated?

Linux 5.10rc5 and newer.

**Comment by jwrdegoede** [comment]
It has also been backported to 5.9.11 and later.

**Comment by ijonglin** [comment]
coolness.  I've assigned myself a new task to validate for the Teclast F5.
