### ISSUE TITLE
Wifi not supported

### ISSUE THREAD

**Issue by 101Robotics** [ijonglin/teclast-f5-ubuntu-finalizer#8]
Hello,

I have installed ubuntu 20.04 today and thought that adding your packages would help to get the wifi to work.

I followed your instructions for pre-compiled mods (bios and packages) but ubuntu can't find a "supported wifi adapter" (it worked on windows). I have tried different solutions found on the internet : 
- Adding the code for the 3165 from intel to /lib/firmware https://www.intel.com/content/www/us/en/support/articles/000005511/network-and-io/wireless.html 
- and tried to rename them like they do here : https://itectec.com/ubuntu/ubuntu-how-to-install-intel-dual-band-wireless-ac-3165-drivers/
- also tried this one (in french) : https://www.debian-fr.org/t/tuto-carte-wifi-intel-dual-band-wireless-ac-3165-sur-jessie-debian-8/71424 
- Tried **"dmesg | grep iwl"** but it returns nothing and **"rfkill list all"** only returns the Bluetooth hci0 : 
0: hci0: Bluetooth
    Soft blocked : no
    Hard blocked : no
(found these commands here : https://ubuntuforums.org/showthread.php?t=2382682 )

I am able to connect to the internet through the Bluetooth connection but it's only a few kB/s.

Have you been through a similar problem? Do you have an idea to solve it?

Thank you for your great work :) 

EDIT: I have version 3.05 of the BIOS, I think I will try to update to 3.06 as recommended here: https://techtablets.com/forum/topic/teclast-f5-bios-update/

**Comment by 101Robotics** [comment]
I'm sorry for creating an issue for something that had nothing to do with your work, I reinstalled Windows to update the BIOS to 2.06 and the wifi now works.

Have a nice day.

**Comment by ijonglin** [comment]
@101Robotics Glad to be of some use.
